apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "scoutvision-*"
    jsonData:
      esVersion: "8.11.0"
      timeField: "@timestamp"
      logMessageField: "message"
      logLevelField: "level"
      dataFormat: "logs"

  - name: TimescaleDB
    type: postgres
    access: proxy
    url: timescaledb:5432
    database: scout_metrics
    user: scout_admin
    secureJsonData:
      password: ScoutVision2024!
    jsonData:
      sslmode: disable
    editable: true